package studio.environment.server.definition;

import static org.junit.jupiter.api.Assertions.*;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Map;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;
import tools.jackson.databind.node.ArrayNode;
import tools.jackson.databind.node.ObjectNode;
import studio.environment.core.definitionv3.NativeCompilationResult;

/** Contract qualification using invented fixture variants and independent Python framing. */
class NativeV3CompatibilityTest {
    private static final JsonMapper JSON = JsonMapper.builder().build();
    private final NativeV3DefinitionBytesCompiler compiler = new NativeV3DefinitionBytesCompiler();
    private ObjectNode fixture() throws Exception {
        return (ObjectNode) JSON.readTree(Files.readAllBytes(Path.of("../../fixtures/native-v3/definition.json")));
    }
    private NativeCompilationResult.Checked checked(JsonNode input) {
        return assertInstanceOf(NativeCompilationResult.Incomplete.class,
                compiler.compile(JSON.writeValueAsBytes(input), DefinitionBytesCompiler.Format.JSON)).checked();
    }
    @Test void sourceOrderingAndMetadataPreserveEveryOriginalDigest() throws Exception {
        var original = fixture(); var expected = checked(original); var changed = original.deepCopy();
        changed.put("id", "another-neutral-id"); changed.put("revision", BigInteger.TEN.pow(100));
        var logical = changed.get("logical");
        logical.properties().forEach(entry -> reverse((ArrayNode) entry.getValue()));
        logical.get("entityTypes").forEach(type -> {
            ((ObjectNode) type).put("label", "Another label 𐀀"); reverse((ArrayNode) type.get("fields"));
        });
        logical.get("computedTypes").forEach(type -> ((ObjectNode) type).put("label", "Another computed label 𐀀"));
        reverse((ArrayNode) changed.get("bindings"));
        changed.get("bindings").forEach(binding -> {
            reverse((ArrayNode) binding.get("documents"));
            binding.get("documents").forEach(document -> {
                reverse((ArrayNode) document.get("entities"));
                document.get("entities").forEach(projection -> {
                    reverse((ArrayNode) projection.get("fields")); reverse((ArrayNode) projection.get("references"));
                });
            });
        });
        var actual = checked(changed);
        assertEquals(expected.logicalDigest(), actual.logicalDigest());
        assertEquals(expected.bindingDigests(), actual.bindingDigests());
        assertEquals(expected.mechanisms(), actual.mechanisms());
    }
    @Test void directionalAndUnicodeIntegerVariantsMatchIndependentFixedDigests() throws Exception {
        // Generated by fixtures/native-v3/digest-oracle.py functions, independently of Java.
        var inverted = fixture(); var pair = (ObjectNode) inverted.at("/logical/cooccurrences/0");
        pair.put("fromDerivation", "by-finish"); pair.put("toDerivation", "by-tone");
        var result = checked(inverted);
        assertEquals("6cab5ae476cb5b4032b6e653c1ebc463f770870c5630f9ed72829dfbf0ed8c15", result.logicalDigest());
        assertEquals(Map.of("mock-pg", "d3b0a8cdebe3a4553a7d906bbe86e00b8f15677691b89916eb99d19587c5c343",
                "mock-oracle", "e043a7dfae319fd303bbb8d7733ca1c0f51e5c4c94d5d4c04dbca3249a0370f7"), result.bindingDigests());
        var unicode = fixture(); unicode.put("revision", BigInteger.TEN.pow(100));
        ((ObjectNode) unicode.at("/logical/cooccurrences/0")).put("maximum", BigInteger.TEN.pow(100));
        ((ObjectNode) unicode.at("/bindings/0/documents/0/entities/0/fields/1/childProperty"))
                .put("discriminatorValue", "e\u0301\uE000\uD800\uDC00\t");
        result = checked(unicode);
        assertEquals("65a9be6d50d415a931f49f377ebbc58b83ec0a4b4b3baa72386154809be988a6", result.logicalDigest());
        assertEquals(Map.of("mock-pg", "1b5418d95136aec13081284a22e7d290764e324ee073820a3360411d3cff3100",
                "mock-oracle", "30d95fdf28d8200ec653f8052bcf872da21cd3fc3c8d3da606b33fd8e23b7563"), result.bindingDigests());
    }
    private static void reverse(ArrayNode nodes) {
        var values = new ArrayList<JsonNode>(); nodes.forEach(values::add); Collections.reverse(values);
        nodes.removeAll(); values.forEach(nodes::add);
    }
}
