package studio.environment.supervisor;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class SessionEngineTest {
    static final class Scripted implements SessionEngine.Wire {
        final List<String> calls=new ArrayList<>();String failure="";boolean error;SessionEngine.Cleanup cleanup=SessionEngine.Cleanup.COMPLETE;
        void step(String value){calls.add(value);if(value.equals(failure)){if(error)throw new AssertionError("INDEPENDENT_ERROR");throw new Refusal("INDEPENDENT_FAILURE");}}
        public void authenticate(){step("authenticate");}public void bootstrap(){step("bootstrap");}public void program(){step("program");}public void readiness(){step("ready");}public void commit(){step("commit");}public void acknowledgement(){step("acknowledgement");}public void cleanExit(){step("cleanExit");}public SessionEngine.Cleanup rollbackAndCleanup(){step("rollback");return cleanup;}public void terminate(){step("terminate");}public void close(){step("close");}
    }
    @Test void exactlyOneCommitRequiresReadinessAndAcknowledgementAndCleanExit(){var wire=new Scripted();assertEquals(new SessionEngine.Outcome(SessionEngine.Status.APPLIED,SessionEngine.Cleanup.COMPLETE),new SessionEngine().execute(wire));assertEquals(List.of("authenticate","bootstrap","program","ready","commit","acknowledgement","cleanExit","close"),wire.calls);}
    @Test void everyPrecommitFailurePermanentlyPreventsCommit(){for(String failure:List.of("authenticate","bootstrap","program","ready")){var wire=new Scripted();wire.failure=failure;var result=new SessionEngine().execute(wire);assertEquals(SessionEngine.Status.NOT_APPLIED,result.status());assertFalse(wire.calls.contains("commit"));assertEquals(SessionEngine.Cleanup.COMPLETE,result.cleanup());}}
    @Test void uncertainCommitDeliveryOrAcknowledgementNeverRetriesOrClaimsRollback(){for(String failure:List.of("commit","acknowledgement","cleanExit")){var wire=new Scripted();wire.failure=failure;var result=new SessionEngine().execute(wire);assertEquals(SessionEngine.Status.UNKNOWN,result.status());assertEquals(SessionEngine.Cleanup.INCONCLUSIVE,result.cleanup());assertEquals(1,Collections.frequency(wire.calls,"commit"));assertFalse(wire.calls.contains("rollback"));}}
    @Test void processDeathAloneCannotEstablishCleanup(){var wire=new Scripted();wire.failure="ready";wire.cleanup=SessionEngine.Cleanup.INCONCLUSIVE;assertEquals(SessionEngine.Cleanup.INCONCLUSIVE,new SessionEngine().execute(wire).cleanup());}
    @Test void toolCleanupFailureDoesNotEraseAcknowledgedOutcome(){var wire=new Scripted();wire.failure="close";assertEquals(new SessionEngine.Outcome(SessionEngine.Status.APPLIED,SessionEngine.Cleanup.INCONCLUSIVE),new SessionEngine().execute(wire));}
    @Test void errorsDuringCommitAndAcknowledgementRetainUnknownAndAttemptOwnedCleanup(){for(String failure:List.of("commit","acknowledgement")){var wire=new Scripted();wire.failure=failure;wire.error=true;var result=assertDoesNotThrow(()->new SessionEngine().execute(wire));assertEquals(new SessionEngine.Outcome(SessionEngine.Status.UNKNOWN,SessionEngine.Cleanup.INCONCLUSIVE),result);assertTrue(wire.calls.contains("terminate"));assertEquals("close",wire.calls.getLast());assertEquals(1,Collections.frequency(wire.calls,"commit"));}}
    @Test void errorDuringClosePreservesAcknowledgedApplied(){var wire=new Scripted();wire.failure="close";wire.error=true;assertEquals(new SessionEngine.Outcome(SessionEngine.Status.APPLIED,SessionEngine.Cleanup.INCONCLUSIVE),assertDoesNotThrow(()->new SessionEngine().execute(wire)));}
    @Test void precommitErrorStillAttemptsRollbackAndClose(){var wire=new Scripted();wire.failure="ready";wire.error=true;assertEquals(new SessionEngine.Outcome(SessionEngine.Status.NOT_APPLIED,SessionEngine.Cleanup.COMPLETE),assertDoesNotThrow(()->new SessionEngine().execute(wire)));assertFalse(wire.calls.contains("commit"));assertTrue(wire.calls.contains("rollback"));assertEquals("close",wire.calls.getLast());}
}
