package studio.environment.server.export;

/** Inspects container/metadata only. No transaction template is qualified or generated by this slice. */
public final class GuardedPackageInspector {
    public sealed interface Result {
        record Unqualified(PackageData.Execution execution,PackageData.Payload payload,PackageData.Counts counts,String archiveDigest,String programDigest)implements Result {
            public String code(){return "TEMPLATE_QUALIFICATION_UNAVAILABLE";}
            @Override public String toString(){return "UnqualifiedPackage[redacted,generation-unavailable]";}
        }
        record Rejected(String code)implements Result { }
    }
    public Result inspect(byte[] archive){
        try {
            var decoded=new StrictPackageZip().read(archive);if(decoded instanceof StrictPackageZip.ReadResult.Rejected refused)return new Result.Rejected(refused.code());
            var members=((StrictPackageZip.ReadResult.Decoded)decoded).members();var admission=new PackageAdmission();var manifest=admission.manifest(members.get(0).bytes());
            for(int i=1;i<4;i++){
                var member=members.get(i);byte[]bytes=member.bytes();var declared=manifest.get("members").get(member.name());
                if(declared.get("bytes").longValue()!=bytes.length || !declared.get("sha256").asString().equals(PackageJson.sha256(bytes)))PackageJson.fail("MEMBER_INTEGRITY_MISMATCH");
            }
            if(!java.util.Arrays.equals(PackageInstructions.bytes(),members.get(3).bytes()))PackageJson.fail("INSTRUCTIONS_MISMATCH");
            PackageJson.utf8(members.get(2).bytes());
            var inputs=admission.read(PackageJson.canonical(manifest.get("execution"),PackageJson.SMALL),members.get(1).bytes());
            if(inputs instanceof PackageAdmission.Result.Rejected refused)return new Result.Rejected(refused.code());
            var accepted=(PackageAdmission.Result.Accepted)inputs;var counts=manifest.get("counts");
            if(!accepted.programDigest().equals(manifest.get("programDigest").asString()))PackageJson.fail("PROGRAM_DIGEST_MISMATCH");
            if(counts.get("records").intValue()!=accepted.counts().records() || counts.get("changedRecords").intValue()!=accepted.counts().changedRecords() || counts.get("originalBytes").longValue()!=accepted.counts().originalBytes() || counts.get("targetBytes").longValue()!=accepted.counts().targetBytes())PackageJson.fail("COUNT_MISMATCH");
            return new Result.Unqualified(accepted.execution(),accepted.payload(),accepted.counts(),PackageJson.sha256(archive),accepted.programDigest());
        }catch(PackageJson.Refusal refused){return new Result.Rejected(refused.code);}
    }
    public boolean generationAvailable(){return false;}
}
