#include "privacy-compiled.h"
#ifndef ES_FIXTURE_PARENT
#error fixture parent must be generated by the exclusive test harness
#endif
#ifndef ES_FIXTURE_JAVA
#error fixture JDK identity must be generated by the test harness
#endif
/* Independently invented, separately linked test-only records. No identity strategy. */
static const es_compiled_mechanism mechanism={1,ES_FIXTURE_JAVA,ES_FIXTURE_PARENT,1};
static const es_compiled_chain chain={.ordinal=1,.mechanism=1,.version=1,.width=1,.identity_version=0,.lifetime=180000000000ULL,.installation={1},.chain={2}};
const es_compiled_mechanism *es_compiled_find_mechanism(int ordinal){return ordinal==1?&mechanism:0;}
const es_compiled_chain *es_compiled_find_chain(int ordinal){return ordinal==1?&chain:0;}
